import SessionProvider from "./utils/SessionProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const getProfile = () => {
  return new Promise((resolve) => {
    resolve({ name: "Hoàng An", email: "hoangan.web@gmail.com" });
  });
};

export default async function RootLayout({ children }) {
  const profile = await getProfile();
  return (
    <html lang="en">
      <body>
        <SessionProvider sessionData={profile}>{children}</SessionProvider>
      </body>
    </html>
  );
}
